### ISSUE TITLE
wct 3.0.3 does not propagate the operatorContactUrl to Heritrix 3

### ISSUE THREAD

**Issue by vitezg** [WebCuratorTool/webcurator#38]
We've set up WCT and set the operator contact URL in the profile, however this data does not seem to propagate to the heritrix job configuration. I've attached four screenshots. Any idea what the problem can be? 
![screenshot](https://user-images.githubusercontent.com/745368/121887561-6b61c700-cd06-11eb-83b5-10c6a360d569.png)
![screenshot1](https://user-images.githubusercontent.com/745368/121887564-6bfa5d80-cd06-11eb-84a5-65b11fac5565.png)
![screenshot2](https://user-images.githubusercontent.com/745368/121887567-6c92f400-cd06-11eb-985c-e2c91de12ade.png)
![screenshot3](https://user-images.githubusercontent.com/745368/121887569-6dc42100-cd06-11eb-90fd-59d1c35a8720.png)

**Comment by obrienben** [comment]
Hi @vitezg, you don't need to explicitly define the OPERATOR_CONTACT_URL placeholder in the _User Agent Prefix_ field. It is automatically appended onto the user agent string.
E.g.
![image](https://user-images.githubusercontent.com/5760612/121967561-b80bd780-cdc4-11eb-8bab-5f13737d3187.png)

**Comment by vitezg** [comment]
WCT seems to sets up crawler-beans.cxml properly (first screenshot), however heritrix seems to get a different configuration (second screenshot). I could set the variables as you described, thanks a lot for that, still the issue seems to lie somewhere else.

![screenshot3](https://user-images.githubusercontent.com/745368/122004267-7a9f4e00-cdb4-11eb-95f6-57a0d00dedd2.png)
![screenshot2](https://user-images.githubusercontent.com/745368/122004312-8b4fc400-cdb4-11eb-9dfe-2ebff25897ba.png)

**Comment by obrienben** [comment]
Hi @vitezg what version are you currently running where you are seeing this issue?

**Comment by vitezg** [comment]
It's 3.0.3, wct-binary-3.0.3.tar.gz as downloaded from https://github.com/WebCuratorTool/webcurator/releases
Our heritrix is heritrix-3.4.0-20200518, will try to update it and get back to you.

**Comment by vitezg** [comment]
It's the same with Heritrix 3.4.0-20210621

**Comment by hannakoppelaar** [comment]
Hi @vitezg, my guess is that the profile as stored by WCT is not being sent to Heritrix at all at job creation time. Can you check the logging from webcurator-webapp and webcurator-harvest-agent-h3 right after the moment a WCT target instance is run? Maybe that will give us a clue as to what's going on

**Comment by vitezg** [comment]
Hello @hannakoppelaar , thanks a lot for asking for the logs, you have guided me to the solution :) The problem was that WCT was running with a different user id than heritrix, so it could not write to the heritrix job directory. Running both software with heritrix's account solved all the issues, and the first harvest job just finished!

**Comment by hannakoppelaar** [comment]
That's great news @vitezg! :)
