### ISSUE TITLE
Tree View unresponsive (WCT 3.0.0)

### ISSUE THREAD

**Issue by schmika** [WebCuratorTool/webcurator#42]
When navigating the tree view we have issues with folders containing a large number of URIs. Whenever we try to display the contents of the folder, the webpage stops responding. There are no errors in the WCT log files, as far as I can see.
This happens in WCT 3.0.0. Has anyone come across the same behaviour? Is that something that will be fixed in the new QA functionality in WCT > 3.0.0?
Thanks in advance for any help you can provide.

**Comment by obrienben** [comment]
Yes this is expected behaviour with larger harvests (size or URIs) and the old Tree View, and one of the main reasons for the new QA functionality in 3.1. This whole area has been re-developed to scale with larger harvests.

**Comment by schmika** [comment]
That sounds great, thank you, @obrienben !
