### ISSUE TITLE
When creating a new target record the 'harvester type' in the profile tab defaults to H1 not H3

### ISSUE THREAD

**Issue by gleenz** [WebCuratorTool/webcurator#44]
When creating a new target record the 'harvester type' in the profile tab defaults to H1 not H3. The base profile points correctly to the default Standard Profile.

However when I change H1 to H3 manually the base profile suddenly incorrectly points to the Fast/aggressive profile (the first profile in the list) instead of the default Standard profile.

**Comment by obrienben** [comment]
No longer a bug, unclear when it was resolved
