### ISSUE TITLE
Error when trying to create a subgroup 

### ISSUE THREAD

**Issue by hannakoppelaar** [WebCuratorTool/webcurator#65]
When you try to create a group that is a subgroup of an existing group, you get the error message "java.lang.IllegalStateException: tabEditorContext not yet bound to the session" upon confirming your selection of the parent group.

Steps to reproduce: choose "Create new" in the groups screen and then in the following screen:

![Screenshot 2022-03-16 at 12-35-56 WEB CURATOR TOOL Groups](https://user-images.githubusercontent.com/33447425/158582231-eb6b2b3c-e038-4030-b149-e00711f21b01.png)

choose "Sub-Group" in the Type drop-down and click "Add" next to the Parent Group field. Then, in the next screen:

![Screenshot 2022-03-16 at 12-43-59 WEB CURATOR TOOL Groups](https://user-images.githubusercontent.com/33447425/158582985-108763a4-5d6f-46e5-bdfd-0094a1580f24.png)

choose the parent group and click "Save". This will result in the following screen:

![Screenshot 2022-03-16 at 12-47-15 Error](https://user-images.githubusercontent.com/33447425/158583293-a3ddcd52-5b5c-4fd6-9ea6-47aaf2d4f5cf.png)

**Comment by obrienben** [comment]
Fixed in PR #94
